### ISSUE TITLE
I followed the installation instructions several times and got this error: 

### ISSUE THREAD

**Issue by alistaitsacle** [aws-samples/dify-aws-tool#23]
I followed the installation instructions several times and got this error: 

'''
Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/app/api/app.py", line 25, in <module>
    from commands import register_commands
  File "/app/api/commands.py", line 13, in <module>
    from core.rag.datasource.vdb.vector_factory import Vector
  File "/app/api/core/rag/datasource/vdb/vector_factory.py", line 5, in <module>
    from core.embedding.cached_embedding import CacheEmbedding
  File "/app/api/core/embedding/cached_embedding.py", line 8, in <module>
    from core.model_manager import ModelInstance
  File "/app/api/core/model_manager.py", line 6, in <module>
    from core.entities.provider_configuration import ProviderConfiguration, ProviderModelBundle
  File "/app/api/core/entities/provider_configuration.py", line 28, in <module>
    from core.model_runtime.model_providers import model_provider_factory
  File "/app/api/core/model_runtime/model_providers/__init__.py", line 3, in <module>
    model_provider_factory = ModelProviderFactory()
  File "/app/api/core/model_runtime/model_providers/model_provider_factory.py", line 32, in __init__
    self.get_providers()
  File "/app/api/core/model_runtime/model_providers/model_provider_factory.py", line 53, in get_providers
    models = model_provider_instance.models(model_type)
  File "/app/api/core/model_runtime/model_providers/__base/model_provider.py", line 72, in models
    model_instance = self.get_model_instance(model_type)
  File "/app/api/core/model_runtime/model_providers/__base/model_provider.py", line 104, in get_model_instance
    mod = import_module_from_source(
  File "/app/api/core/helper/module_import_helper.py", line 33, in import_module_from_source
    raise e
  File "/app/api/core/helper/module_import_helper.py", line 29, in import_module_from_source
    spec.loader.exec_module(module)
  File "/app/api/core/model_runtime/model_providers/sagemaker/llm/llm.py", line 6, in <module>
    from sagemaker import Predictor
ModuleNotFoundError: No module named 'sagemaker'

Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: No such command 'upgrade-db'.
Running migrations
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
ERROR:root:Failed to load module core.model_runtime.model_providers.sagemaker.llm.llm from /app/api/core/model_runtime/model_providers/sagemaker/llm/llm.py: No module named 'sagemaker'
Traceback (most recent call last):
  File "/app/api/core/helper/module_import_helper.py", line 29, in import_module_from_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/api/core/model_runtime/model_providers/sagemaker/llm/llm.py", line 6, in <module>
    from sagemaker import Predictor
ModuleNotFoundError: No module named 'sagemaker'
Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/app/api/app.py", line 25, in <module>
    from commands import register_commands
  File "/app/api/commands.py", line 13, in <module>
    from core.rag.datasource.vdb.vector_factory import Vector
  File "/app/api/core/rag/datasource/vdb/vector_factory.py", line 5, in <module>
    from core.embedding.cached_embedding import CacheEmbedding
  File "/app/api/core/embedding/cached_embedding.py", line 8, in <module>
    from core.model_manager import ModelInstance
  File "/app/api/core/model_manager.py", line 6, in <module>
    from core.entities.provider_configuration import ProviderConfiguration, ProviderModelBundle
  File "/app/api/core/entities/provider_configuration.py", line 28, in <module>
    from core.model_runtime.model_providers import model_provider_factory
  File "/app/api/core/model_runtime/model_providers/__init__.py", line 3, in <module>
    model_provider_factory = ModelProviderFactory()
  File "/app/api/core/model_runtime/model_providers/model_provider_factory.py", line 32, in __init__
    self.get_providers()
  File "/app/api/core/model_runtime/model_providers/model_provider_factory.py", line 53, in get_providers
    models = model_provider_instance.models(model_type)
  File "/app/api/core/model_runtime/model_providers/__base/model_provider.py", line 72, in models
    model_instance = self.get_model_instance(model_type)
  File "/app/api/core/model_runtime/model_providers/__base/model_provider.py", line 104, in get_model_instance
    mod = import_module_from_source(
  File "/app/api/core/helper/module_import_helper.py", line 33, in import_module_from_source
    raise e
  File "/app/api/core/helper/module_import_helper.py", line 29, in import_module_from_source
    spec.loader.exec_module(module)
  File "/app/api/core/model_runtime/model_providers/sagemaker/llm/llm.py", line 6, in <module>
    from sagemaker import Predictor
ModuleNotFoundError: No module named 'sagemaker'

Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: No such command 'upgrade-db'.
Running migrations
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
ERROR:root:Failed to load module core.model_runtime.model_providers.sagemaker.llm.llm from /app/api/core/model_runtime/model_providers/sagemaker/llm/llm.py: No module named 'sagemaker'
Traceback (most recent call last):
  File "/app/api/core/helper/module_import_helper.py", line 29, in import_module_from_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/api/core/model_runtime/model_providers/sagemaker/llm/llm.py", line 6, in <module>
    from sagemaker import Predictor
ModuleNotFoundError: No module named 'sagemaker'
Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/app/api/app.py", line 25, in <module>
    from commands import register_commands
  File "/app/api/commands.py", line 13, in <module>
    from core.rag.datasource.vdb.vector_factory import Vector
  File "/app/api/core/rag/datasource/vdb/vector_factory.py", line 5, in <module>
    from core.embedding.cached_embedding import CacheEmbedding
  File "/app/api/core/embedding/cached_embedding.py", line 8, in <module>
    from core.model_manager import ModelInstance
  File "/app/api/core/model_manager.py", line 6, in <module>
    from core.entities.provider_configuration import ProviderConfiguration, ProviderModelBundle
  File "/app/api/core/entities/provider_configuration.py", line 28, in <module>
    from core.model_runtime.model_providers import model_provider_factory
  File "/app/api/core/model_runtime/model_providers/__init__.py", line 3, in <module>
    model_provider_factory = ModelProviderFactory()
  File "/app/api/core/model_runtime/model_providers/model_provider_factory.py", line 32, in __init__
    self.get_providers()
  File "/app/api/core/model_runtime/model_providers/model_provider_factory.py", line 53, in get_providers
    models = model_provider_instance.models(model_type)
  File "/app/api/core/model_runtime/model_providers/__base/model_provider.py", line 72, in models
    model_instance = self.get_model_instance(model_type)
  File "/app/api/core/model_runtime/model_providers/__base/model_provider.py", line 104, in get_model_instance
    mod = import_module_from_source(
  File "/app/api/core/helper/module_import_helper.py", line 33, in import_module_from_source
    raise e
  File "/app/api/core/helper/module_import_helper.py", line 29, in import_module_from_source
    spec.loader.exec_module(module)
  File "/app/api/core/model_runtime/model_providers/sagemaker/llm/llm.py", line 6, in <module>
    from sagemaker import Predictor
ModuleNotFoundError: No module named 'sagemaker'

Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: No such command 'upgrade-db'.
'''

**Comment by ybalbert001** [comment]
All these tools and models have been integrated into [dify](https://github.com/langgenius/dify) main branch. It's should be available on dify - 0.8.3 release. No more extra installation needed now.
